// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1FQvT0Dk3vHSbCVdKp5j6MnaiLtza3U',
    appId: '1:444579077755:web:554fed77b80eaf35618cde',
    messagingSenderId: '444579077755',
    projectId: 'calmmind-13b33',
    authDomain: 'calmmind-13b33.firebaseapp.com',
    storageBucket: 'calmmind-13b33.firebasestorage.app',
    measurementId: 'G-STF3TVM4H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe0qKz_xrOIt9HVXDdF7ncUOORWhuF6JE',
    appId: '1:444579077755:android:7c7afdabe375b1be618cde',
    messagingSenderId: '444579077755',
    projectId: 'calmmind-13b33',
    storageBucket: 'calmmind-13b33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxqcZml1_dmqFjZYzlrcl4Z0Wp8q_R9A',
    appId: '1:444579077755:ios:009a8d3e8cb570a1618cde',
    messagingSenderId: '444579077755',
    projectId: 'calmmind-13b33',
    storageBucket: 'calmmind-13b33.firebasestorage.app',
    iosBundleId: 'com.example.calmMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLxqcZml1_dmqFjZYzlrcl4Z0Wp8q_R9A',
    appId: '1:444579077755:ios:009a8d3e8cb570a1618cde',
    messagingSenderId: '444579077755',
    projectId: 'calmmind-13b33',
    storageBucket: 'calmmind-13b33.firebasestorage.app',
    iosBundleId: 'com.example.calmMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP1FQvT0Dk3vHSbCVdKp5j6MnaiLtza3U',
    appId: '1:444579077755:web:9765d6d831ef1d25618cde',
    messagingSenderId: '444579077755',
    projectId: 'calmmind-13b33',
    authDomain: 'calmmind-13b33.firebaseapp.com',
    storageBucket: 'calmmind-13b33.firebasestorage.app',
    measurementId: 'G-41FJX2QPYQ',
  );
}
